version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
    groups:
      androidx:
        patterns:
          - "androidx.*"
      firebase:
        patterns:
          - "com.google.firebase:*"
      kotlin:
        patterns:
          - "org.jetbrains.kotlin*"
          - "org.jetbrains.kotlinx:*"
          - "com.google.devtools.ksp*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
    groups:
      actions:
        patterns:
          - "*"
