complexity:
  ComplexCondition:
    threshold: 5
  CyclomaticComplexMethod:
    ignoreAnnotated: ['Composable']
  LongMethod:
    ignoreAnnotated: ['Composable']
  LongParameterList:
    ignoreAnnotated: ['Composable', 'FormUrlEncoded']
  TooManyFunctions:
    ignoreAnnotated: ['Composable']
    thresholdInClasses: 20

exceptions:
  TooGenericExceptionCaught:
    excludes: ['**/OAuthClient.kt']

naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable']

performance:
  SpreadOperator:
    excludes: ['**/di/**']

style:
  MagicNumber:
    excludes: ['**/ui/**']
    ignorePropertyDeclaration: true
  ReturnCount:
    max: 4
    excludeGuardClauses: true
  UnusedPrivateMember:
    ignoreAnnotated: ['Preview']
