complexity:
  LongMethod:
    ignoreAnnotated: ['Composable']
  LongParameterList:
    ignoreAnnotated: ['Composable']
  TooManyFunctions:
    ignoreAnnotated: ['Composable']

naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable']

style:
  MagicNumber:
    excludes: ['**/ui/**']
  UnusedPrivateMember:
    ignoreAnnotated: ['Preview']
